CREATE TABLE IF NOT EXISTS CarTable (
ID INT NOT NULL,
Brand VARCHAR(20) NOT NULL,
Model VARCHAR(20) NOT NULL,
Colour VARCHAR(20) NOT NULL,
Year INT NOT NULL,
Price DOUBLE NOT NULL,
PRIMARY KEY (ID)
);